# Generated by Django 5.2.1 on 2025-07-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_tcp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tcp',
        ),
    ]
