# Generated by Django 5.2.1 on 2025-07-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_delete_tcp'),
    ]

    operations = [
        migrations.CreateModel(
            name='userroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ursname', models.CharField(max_length=100)),
                ('ursemaile', models.EmailField(default='noemail@example.com', max_length=254)),
            ],
        ),
    ]
