# Generated by Django 5.2.1 on 2025-07-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_userroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroy',
            name='urscontect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userroy',
            name='urspassword',
            field=models.CharField(default='Default Value', max_length=50),
        ),
        migrations.AddField(
            model_name='userroy',
            name='usrstates',
            field=models.BooleanField(default=True),
        ),
    ]
