# Generated by Django 5.2.1 on 2025-07-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_userroy_urscontect_userroy_urspassword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userroy',
        ),
    ]
