# Generated by Django 5.2.1 on 2025-06-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='image',
            field=models.ImageField(upload_to='receipes/'),
        ),
    ]
