# Generated by Django 5.2.1 on 2025-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0002_alter_receipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='mansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
