# Generated by Django 5.2.1 on 2025-07-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0003_mansi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mansi',
            new_name='Tcp',
        ),
    ]
