# Generated by Django 5.2.1 on 2025-07-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0004_rename_mansi_tcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcp',
            name='contact',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
