# Generated by Django 5.2.1 on 2025-07-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0005_alter_tcp_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='userroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ursname', models.CharField(max_length=100)),
                ('ursemaile', models.EmailField(default='noemail@example.com', max_length=254)),
                ('urscontect', models.IntegerField(default=0)),
                ('urspassword', models.CharField(default='Default Value', max_length=50)),
                ('usrstates', models.BooleanField(default=True)),
            ],
        ),
    ]
