# Generated by Django 5.2.1 on 2025-07-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0006_userroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroy',
            old_name='ursemaile',
            new_name='usrEmail',
        ),
        migrations.RenameField(
            model_name='userroy',
            old_name='urscontect',
            new_name='usrcontect',
        ),
        migrations.RenameField(
            model_name='userroy',
            old_name='ursname',
            new_name='usrname',
        ),
        migrations.RenameField(
            model_name='userroy',
            old_name='urspassword',
            new_name='usrpassword',
        ),
    ]
