# Generated by Django 5.2.1 on 2025-07-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0007_rename_ursemaile_userroy_usremail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ptnsmasten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasname', models.CharField(max_length=100)),
                ('pascontact', models.EmailField(max_length=254)),
                ('pasaddress', models.CharField()),
                ('pascity', models.CharField()),
                ('pasStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
