# Generated by Django 5.2.1 on 2025-07-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0008_ptnsmasten'),
    ]

    operations = [
        migrations.CreateModel(
            name='userps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=100)),
                ('usrEmail', models.EmailField(default='noemail@example.com', max_length=254)),
                ('usrcontect', models.IntegerField(default=0)),
                ('usrpassword', models.CharField(default='Default Value', max_length=50)),
                ('usrstates', models.BooleanField(default=True)),
            ],
        ),
    ]
