# Generated by Django 5.2.1 on 2025-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0009_userps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userps',
            name='usrEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userps',
            name='usrcontect',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userps',
            name='usrpassword',
            field=models.CharField(max_length=500),
        ),
    ]
