# Generated by Django 5.2.1 on 2025-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0010_alter_userps_usremail_alter_userps_usrcontect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userps',
            old_name='usrname',
            new_name='UsrPassword',
        ),
        migrations.RemoveField(
            model_name='userps',
            name='usrEmail',
        ),
        migrations.RemoveField(
            model_name='userps',
            name='usrcontect',
        ),
        migrations.RemoveField(
            model_name='userps',
            name='usrpassword',
        ),
        migrations.RemoveField(
            model_name='userps',
            name='usrstates',
        ),
        migrations.AddField(
            model_name='userps',
            name='UsrEmaile',
            field=models.EmailField(default=64, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userps',
            name='Usrname',
            field=models.CharField(default=65, max_length=100),
            preserve_default=False,
        ),
    ]
