# Generated by Django 5.2.1 on 2025-07-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0011_rename_usrname_userps_usrpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userps',
            name='UsrEmaile',
            field=models.EmailField(max_length=254),
        ),
    ]
